# Copyright (C) 2017 The Ubports Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

PRODUCT_COPY_FILES += \
    vendor/sony/sumire/vendor/firmware/keymaster/keymaster.b00:system/vendor/firmware/keymaster/keymaster.b00 \
    vendor/sony/sumire/vendor/firmware/keymaster/keymaster.b01:system/vendor/firmware/keymaster/keymaster.b01 \
    vendor/sony/sumire/vendor/firmware/keymaster/keymaster.b02:system/vendor/firmware/keymaster/keymaster.b02 \
    vendor/sony/sumire/vendor/firmware/keymaster/keymaster.b03:system/vendor/firmware/keymaster/keymaster.b03 \
    vendor/sony/sumire/vendor/firmware/keymaster/keymaster.mdt:system/vendor/firmware/keymaster/keymaster.mdt \
    vendor/sony/sumire/vendor/firmware/tzfingerprint.b00:system/vendor/firmware/tzfingerprint.b00 \
    vendor/sony/sumire/vendor/firmware/tzfingerprint.b01:system/vendor/firmware/tzfingerprint.b01 \
    vendor/sony/sumire/vendor/firmware/tzfingerprint.b02:system/vendor/firmware/tzfingerprint.b02 \
    vendor/sony/sumire/vendor/firmware/tzfingerprint.b03:system/vendor/firmware/tzfingerprint.b03 \
    vendor/sony/sumire/vendor/firmware/tzfingerprint.mdt:system/vendor/firmware/tzfingerprint.mdt \
    vendor/sony/kitakami/etc/firmware/a420_pfp.fw:system/etc/firmware/a420_pfp.fw \
    vendor/sony/kitakami/etc/firmware/a420_pm4.fw:system/etc/firmware/a420_pm4.fw \
    vendor/sony/kitakami/etc/firmware/cmnlib.b00:system/etc/firmware/cmnlib.b00 \
    vendor/sony/kitakami/etc/firmware/cmnlib.b01:system/etc/firmware/cmnlib.b01 \
    vendor/sony/kitakami/etc/firmware/cmnlib.b02:system/etc/firmware/cmnlib.b02 \
    vendor/sony/kitakami/etc/firmware/cmnlib.b03:system/etc/firmware/cmnlib.b03 \
    vendor/sony/kitakami/etc/firmware/cmnlib.mdt:system/etc/firmware/cmnlib.mdt \
    vendor/sony/kitakami/etc/firmware/cpp_firmware_v1_8_0.fw:system/etc/firmware/cpp_firmware_v1_8_0.fw \
    vendor/sony/kitakami/etc/firmware/fidocrypto.b00:system/etc/firmware/fidocrypto.b00 \
    vendor/sony/kitakami/etc/firmware/fidocrypto.b01:system/etc/firmware/fidocrypto.b01 \
    vendor/sony/kitakami/etc/firmware/fidocrypto.b02:system/etc/firmware/fidocrypto.b02 \
    vendor/sony/kitakami/etc/firmware/fidocrypto.b03:system/etc/firmware/fidocrypto.b03 \
    vendor/sony/kitakami/etc/firmware/fidocrypto.mdt:system/etc/firmware/fidocrypto.mdt \
    vendor/sony/kitakami/etc/firmware/tzdtcpkctl.b00:system/etc/firmware/tzdtcpkctl.b00 \
    vendor/sony/kitakami/etc/firmware/tzdtcpkctl.b01:system/etc/firmware/tzdtcpkctl.b01 \
    vendor/sony/kitakami/etc/firmware/tzdtcpkctl.b02:system/etc/firmware/tzdtcpkctl.b02 \
    vendor/sony/kitakami/etc/firmware/tzdtcpkctl.b03:system/etc/firmware/tzdtcpkctl.b03 \
    vendor/sony/kitakami/etc/firmware/tzdtcpkctl.mdt:system/etc/firmware/tzdtcpkctl.mdt \
    vendor/sony/kitakami/etc/firmware/tzhdcp.b00:system/etc/firmware/tzhdcp.b00 \
    vendor/sony/kitakami/etc/firmware/tzhdcp.b01:system/etc/firmware/tzhdcp.b01 \
    vendor/sony/kitakami/etc/firmware/tzhdcp.b02:system/etc/firmware/tzhdcp.b02 \
    vendor/sony/kitakami/etc/firmware/tzhdcp.b03:system/etc/firmware/tzhdcp.b03 \
    vendor/sony/kitakami/etc/firmware/tzhdcp.mdt:system/etc/firmware/tzhdcp.mdt \
    vendor/sony/kitakami/etc/firmware/tzlibasb.b00:system/etc/firmware/tzlibasb.b00 \
    vendor/sony/kitakami/etc/firmware/tzlibasb.b01:system/etc/firmware/tzlibasb.b01 \
    vendor/sony/kitakami/etc/firmware/tzlibasb.b02:system/etc/firmware/tzlibasb.b02 \
    vendor/sony/kitakami/etc/firmware/tzlibasb.b03:system/etc/firmware/tzlibasb.b03 \
    vendor/sony/kitakami/etc/firmware/tzlibasb.mdt:system/etc/firmware/tzlibasb.mdt \
    vendor/sony/kitakami/etc/firmware/tznautilus.b00:system/etc/firmware/tznautilus.b00 \
    vendor/sony/kitakami/etc/firmware/tznautilus.b01:system/etc/firmware/tznautilus.b01 \
    vendor/sony/kitakami/etc/firmware/tznautilus.b02:system/etc/firmware/tznautilus.b02 \
    vendor/sony/kitakami/etc/firmware/tznautilus.b03:system/etc/firmware/tznautilus.b03 \
    vendor/sony/kitakami/etc/firmware/tznautilus.mdt:system/etc/firmware/tznautilus.mdt \
    vendor/sony/kitakami/etc/firmware/tzsuntory.b00:system/etc/firmware/tzsuntory.b00 \
    vendor/sony/kitakami/etc/firmware/tzsuntory.b01:system/etc/firmware/tzsuntory.b01 \
    vendor/sony/kitakami/etc/firmware/tzsuntory.b02:system/etc/firmware/tzsuntory.b02 \
    vendor/sony/kitakami/etc/firmware/tzsuntory.b03:system/etc/firmware/tzsuntory.b03 \
    vendor/sony/kitakami/etc/firmware/tzsuntory.mdt:system/etc/firmware/tzsuntory.mdt \
    vendor/sony/kitakami/etc/firmware/tztpm.b00:system/etc/firmware/tztpm.b00 \
    vendor/sony/kitakami/etc/firmware/tztpm.b01:system/etc/firmware/tztpm.b01 \
    vendor/sony/kitakami/etc/firmware/tztpm.b02:system/etc/firmware/tztpm.b02 \
    vendor/sony/kitakami/etc/firmware/tztpm.b03:system/etc/firmware/tztpm.b03 \
    vendor/sony/kitakami/etc/firmware/tztpm.mdt:system/etc/firmware/tztpm.mdt \
    vendor/sony/kitakami/etc/firmware/tzwidevine.b00:system/etc/firmware/tzwidevine.b00 \
    vendor/sony/kitakami/etc/firmware/tzwidevine.b01:system/etc/firmware/tzwidevine.b01 \
    vendor/sony/kitakami/etc/firmware/tzwidevine.b02:system/etc/firmware/tzwidevine.b02 \
    vendor/sony/kitakami/etc/firmware/tzwidevine.b03:system/etc/firmware/tzwidevine.b03 \
    vendor/sony/kitakami/etc/firmware/tzwidevine.mdt:system/etc/firmware/tzwidevine.mdt \
    vendor/sony/kitakami/etc/firmware/tzwvcpybuf.b00:system/etc/firmware/tzwvcpybuf.b00 \
    vendor/sony/kitakami/etc/firmware/tzwvcpybuf.b01:system/etc/firmware/tzwvcpybuf.b01 \
    vendor/sony/kitakami/etc/firmware/tzwvcpybuf.b02:system/etc/firmware/tzwvcpybuf.b02 \
    vendor/sony/kitakami/etc/firmware/tzwvcpybuf.b03:system/etc/firmware/tzwvcpybuf.b03 \
    vendor/sony/kitakami/etc/firmware/tzwvcpybuf.mdt:system/etc/firmware/tzwvcpybuf.mdt \
    vendor/sony/kitakami/etc/firmware/venus.b00:system/etc/firmware/venus.b00 \
    vendor/sony/kitakami/etc/firmware/venus.b01:system/etc/firmware/venus.b01 \
    vendor/sony/kitakami/etc/firmware/venus.b02:system/etc/firmware/venus.b02 \
    vendor/sony/kitakami/etc/firmware/venus.b03:system/etc/firmware/venus.b03 \
    vendor/sony/kitakami/etc/firmware/venus.b04:system/etc/firmware/venus.b04 \
    vendor/sony/kitakami/etc/firmware/venus.mdt:system/etc/firmware/venus.mdt \
    vendor/sony/kitakami/vendor/firmware/libpn547_fw.so:system/vendor/firmware/libpn547_fw.so \
    vendor/sony/qcom/adreno/a4xx/vendor/lib/egl/eglSubDriverAndroid.so:system/vendor/lib/egl/eglSubDriverAndroid.so \
    vendor/sony/qcom/adreno/a4xx/vendor/lib/egl/libEGL_adreno.so:system/vendor/lib/egl/libEGL_adreno.so \
    vendor/sony/qcom/adreno/a4xx/vendor/lib/egl/libEGL_adreno.so:system/vendor/lib/libEGL_adreno.so \
    vendor/sony/qcom/adreno/a4xx/vendor/lib/egl/libGLESv1_CM_adreno.so:system/vendor/lib/egl/libGLESv1_CM_adreno.so \
    vendor/sony/qcom/adreno/a4xx/vendor/lib/egl/libGLESv2_adreno.so:system/vendor/lib/egl/libGLESv2_adreno.so \
    vendor/sony/qcom/adreno/a4xx/vendor/lib/egl/libQTapGLES.so:system/vendor/lib/egl/libQTapGLES.so \
    vendor/sony/qcom/adreno/a4xx/vendor/lib/egl/libq3dtools_adreno.so:system/vendor/lib/egl/libq3dtools_adreno.so \
    vendor/sony/qcom/adreno/a4xx/vendor/lib/egl/libq3dtools_esx.so:system/vendor/lib/egl/libq3dtools_esx.so \
    vendor/sony/qcom/adreno/a4xx/vendor/lib/libC2D2.so:system/vendor/lib/libC2D2.so \
    vendor/sony/qcom/adreno/a4xx/vendor/lib/libCB.so:system/vendor/lib/libCB.so \
    vendor/sony/qcom/adreno/a4xx/vendor/lib/libOpenCL.so:system/vendor/lib/libOpenCL.so \
    vendor/sony/qcom/adreno/a4xx/vendor/lib/libRSDriver_adreno.so:system/vendor/lib/libRSDriver_adreno.so \
    vendor/sony/qcom/adreno/a4xx/vendor/lib/libadreno_utils.so:system/vendor/lib/libadreno_utils.so \
    vendor/sony/qcom/adreno/a4xx/vendor/lib/libc2d30-a3xx.so:system/vendor/lib/libc2d30-a3xx.so \
    vendor/sony/qcom/adreno/a4xx/vendor/lib/libc2d30-a4xx.so:system/vendor/lib/libc2d30-a4xx.so \
    vendor/sony/qcom/adreno/a4xx/vendor/lib/libgsl.so:system/vendor/lib/libgsl.so \
    vendor/sony/qcom/adreno/a4xx/vendor/lib/libllvm-glnext.so:system/vendor/lib/libllvm-glnext.so \
    vendor/sony/qcom/adreno/a4xx/vendor/lib/libllvm-qcom.so:system/vendor/lib/libllvm-qcom.so \
    vendor/sony/qcom/adreno/a4xx/vendor/lib/libmm-qdcm.so:system/vendor/lib/libmm-qdcm.so \
    vendor/sony/qcom/adreno/a4xx/vendor/lib/librs_adreno.so:system/vendor/lib/librs_adreno.so \
    vendor/sony/qcom/adreno/a4xx/vendor/lib/librs_adreno_sha1.so:system/vendor/lib/librs_adreno_sha1.so \
    vendor/sony/qcom/adreno/a4xx/vendor/lib64/egl/eglSubDriverAndroid.so:system/vendor/lib64/egl/eglSubDriverAndroid.so \
    vendor/sony/qcom/adreno/a4xx/vendor/lib64/egl/libEGL_adreno.so:system/vendor/lib64/egl/libEGL_adreno.so \
    vendor/sony/qcom/adreno/a4xx/vendor/lib64/egl/libGLESv1_CM_adreno.so:system/vendor/lib64/egl/libGLESv1_CM_adreno.so \
    vendor/sony/qcom/adreno/a4xx/vendor/lib64/egl/libGLESv2_adreno.so:system/vendor/lib64/egl/libGLESv2_adreno.so \
    vendor/sony/qcom/adreno/a4xx/vendor/lib64/egl/libQTapGLES.so:system/vendor/lib64/egl/libQTapGLES.so \
    vendor/sony/qcom/adreno/a4xx/vendor/lib64/egl/libq3dtools_adreno.so:system/vendor/lib64/egl/libq3dtools_adreno.so \
    vendor/sony/qcom/adreno/a4xx/vendor/lib64/egl/libq3dtools_esx.so:system/vendor/lib64/egl/libq3dtools_esx.so \
    vendor/sony/qcom/adreno/a4xx/vendor/lib64/libC2D2.so:system/vendor/lib64/libC2D2.so \
    vendor/sony/qcom/adreno/a4xx/vendor/lib64/libCB.so:system/vendor/lib64/libCB.so \
    vendor/sony/qcom/adreno/a4xx/vendor/lib64/libOpenCL.so:system/vendor/lib64/libOpenCL.so \
    vendor/sony/qcom/adreno/a4xx/vendor/lib64/libRSDriver_adreno.so:system/vendor/lib64/libRSDriver_adreno.so \
    vendor/sony/qcom/adreno/a4xx/vendor/lib64/libadreno_utils.so:system/vendor/lib64/libadreno_utils.so \
    vendor/sony/qcom/adreno/a4xx/vendor/lib64/libc2d30-a3xx.so:system/vendor/lib64/libc2d30-a3xx.so \
    vendor/sony/qcom/adreno/a4xx/vendor/lib64/libc2d30-a4xx.so:system/vendor/lib64/libc2d30-a4xx.so \
    vendor/sony/qcom/adreno/a4xx/vendor/lib64/libgsl.so:system/vendor/lib64/libgsl.so \
    vendor/sony/qcom/adreno/a4xx/vendor/lib64/libllvm-glnext.so:system/vendor/lib64/libllvm-glnext.so \
    vendor/sony/qcom/adreno/a4xx/vendor/lib64/libllvm-qcom.so:system/vendor/lib64/libllvm-qcom.so \
    vendor/sony/qcom/adreno/a4xx/vendor/lib64/libmm-qdcm.so:system/vendor/lib64/libmm-qdcm.so \
    vendor/sony/qcom/adreno/a4xx/vendor/lib64/librs_adreno.so:system/vendor/lib64/librs_adreno.so \
    vendor/sony/qcom/adreno/a4xx/vendor/lib64/librs_adreno_sha1.so:system/vendor/lib64/librs_adreno_sha1.so \
    vendor/sony/qcom/msm8994/vendor/bin/irsc_util:system/vendor/bin/irsc_util \
    vendor/sony/qcom/msm8994/vendor/bin/mlog_qmi_service:system/vendor/bin/mlog_qmi_service \
    vendor/sony/qcom/msm8994/vendor/bin/mm-qcamera-daemon:system/vendor/bin/mm-qcamera-daemon \
    vendor/sony/qcom/msm8994/vendor/bin/msm_irqbalance:system/vendor/bin/msm_irqbalance \
    vendor/sony/qcom/msm8994/vendor/bin/netmgrd:system/vendor/bin/netmgrd \
    vendor/sony/qcom/msm8994/vendor/bin/pm-proxy:system/vendor/bin/pm-proxy \
    vendor/sony/qcom/msm8994/vendor/bin/pm-service:system/vendor/bin/pm-service \
    vendor/sony/qcom/msm8994/vendor/bin/qmuxd:system/vendor/bin/qmuxd \
    vendor/sony/qcom/msm8994/vendor/bin/rmt_storage:system/vendor/bin/rmt_storage \
    vendor/sony/qcom/msm8994/vendor/bin/sct_service:system/vendor/bin/sct_service \
    vendor/sony/qcom/msm8994/vendor/bin/sensors.qcom:system/vendor/bin/sensors.qcom \
    vendor/sony/qcom/msm8994/vendor/bin/ta_qmi_service:system/vendor/bin/ta_qmi_service \
    vendor/sony/qcom/msm8994/vendor/bin/tad_static:system/vendor/bin/tad_static \
    vendor/sony/qcom/msm8994/vendor/lib/hw/sensors.msm8994.so:system/vendor/lib/hw/sensors.msm8994.so \
    vendor/sony/qcom/msm8994/vendor/lib/libQSEEComAPI.so:system/vendor/lib/libQSEEComAPI.so \
    vendor/sony/qcom/msm8994/vendor/lib/libactuator_bu64291gwz.so:system/vendor/lib/libactuator_bu64291gwz.so \
    vendor/sony/qcom/msm8994/vendor/lib/libactuator_bu64291gwz_camcorder.so:system/vendor/lib/libactuator_bu64291gwz_camcorder.so \
    vendor/sony/qcom/msm8994/vendor/lib/libactuator_bu64291gwz_camera.so:system/vendor/lib/libactuator_bu64291gwz_camera.so \
    vendor/sony/qcom/msm8994/vendor/lib/libactuator_bu64295g.so:system/vendor/lib/libactuator_bu64295g.so \
    vendor/sony/qcom/msm8994/vendor/lib/libactuator_bu64295g_camcorder.so:system/vendor/lib/libactuator_bu64295g_camcorder.so \
    vendor/sony/qcom/msm8994/vendor/lib/libactuator_bu64295g_camera.so:system/vendor/lib/libactuator_bu64295g_camera.so \
    vendor/sony/qcom/msm8994/vendor/lib/libactuator_dw9719.so:system/vendor/lib/libactuator_dw9719.so \
    vendor/sony/qcom/msm8994/vendor/lib/libactuator_dw9719_camcorder.so:system/vendor/lib/libactuator_dw9719_camcorder.so \
    vendor/sony/qcom/msm8994/vendor/lib/libactuator_dw9719_camera.so:system/vendor/lib/libactuator_dw9719_camera.so \
    vendor/sony/qcom/msm8994/vendor/lib/libadsprpc.so:system/vendor/lib/libadsprpc.so \
    vendor/sony/qcom/msm8994/vendor/lib/libchromatix_imx134_common.so:system/vendor/lib/libchromatix_imx134_common.so \
    vendor/sony/qcom/msm8994/vendor/lib/libchromatix_imx134_cpp_liveshot.so:system/vendor/lib/libchromatix_imx134_cpp_liveshot.so \
    vendor/sony/qcom/msm8994/vendor/lib/libchromatix_imx134_cpp_preview.so:system/vendor/lib/libchromatix_imx134_cpp_preview.so \
    vendor/sony/qcom/msm8994/vendor/lib/libchromatix_imx134_cpp_snapshot.so:system/vendor/lib/libchromatix_imx134_cpp_snapshot.so \
    vendor/sony/qcom/msm8994/vendor/lib/libchromatix_imx134_cpp_video.so:system/vendor/lib/libchromatix_imx134_cpp_video.so \
    vendor/sony/qcom/msm8994/vendor/lib/libchromatix_imx134_default_video.so:system/vendor/lib/libchromatix_imx134_default_video.so \
    vendor/sony/qcom/msm8994/vendor/lib/libchromatix_imx134_liveshot.so:system/vendor/lib/libchromatix_imx134_liveshot.so \
    vendor/sony/qcom/msm8994/vendor/lib/libchromatix_imx134_postproc.so:system/vendor/lib/libchromatix_imx134_postproc.so \
    vendor/sony/qcom/msm8994/vendor/lib/libchromatix_imx134_preview.so:system/vendor/lib/libchromatix_imx134_preview.so \
    vendor/sony/qcom/msm8994/vendor/lib/libchromatix_imx134_snapshot.so:system/vendor/lib/libchromatix_imx134_snapshot.so \
    vendor/sony/qcom/msm8994/vendor/lib/libchromatix_imx200_common.so:system/vendor/lib/libchromatix_imx200_common.so \
    vendor/sony/qcom/msm8994/vendor/lib/libchromatix_imx200_cpp_liveshot.so:system/vendor/lib/libchromatix_imx200_cpp_liveshot.so \
    vendor/sony/qcom/msm8994/vendor/lib/libchromatix_imx200_cpp_preview.so:system/vendor/lib/libchromatix_imx200_cpp_preview.so \
    vendor/sony/qcom/msm8994/vendor/lib/libchromatix_imx200_cpp_snapshot.so:system/vendor/lib/libchromatix_imx200_cpp_snapshot.so \
    vendor/sony/qcom/msm8994/vendor/lib/libchromatix_imx200_cpp_video.so:system/vendor/lib/libchromatix_imx200_cpp_video.so \
    vendor/sony/qcom/msm8994/vendor/lib/libchromatix_imx200_default_video.so:system/vendor/lib/libchromatix_imx200_default_video.so \
    vendor/sony/qcom/msm8994/vendor/lib/libchromatix_imx200_liveshot.so:system/vendor/lib/libchromatix_imx200_liveshot.so \
    vendor/sony/qcom/msm8994/vendor/lib/libchromatix_imx200_postproc.so:system/vendor/lib/libchromatix_imx200_postproc.so \
    vendor/sony/qcom/msm8994/vendor/lib/libchromatix_imx200_preview.so:system/vendor/lib/libchromatix_imx200_preview.so \
    vendor/sony/qcom/msm8994/vendor/lib/libchromatix_imx200_snapshot.so:system/vendor/lib/libchromatix_imx200_snapshot.so \
    vendor/sony/qcom/msm8994/vendor/lib/libchromatix_imx241_common.so:system/vendor/lib/libchromatix_imx241_common.so \
    vendor/sony/qcom/msm8994/vendor/lib/libchromatix_imx241_cpp_liveshot.so:system/vendor/lib/libchromatix_imx241_cpp_liveshot.so \
    vendor/sony/qcom/msm8994/vendor/lib/libchromatix_imx241_cpp_preview.so:system/vendor/lib/libchromatix_imx241_cpp_preview.so \
    vendor/sony/qcom/msm8994/vendor/lib/libchromatix_imx241_cpp_snapshot.so:system/vendor/lib/libchromatix_imx241_cpp_snapshot.so \
    vendor/sony/qcom/msm8994/vendor/lib/libchromatix_imx241_cpp_video.so:system/vendor/lib/libchromatix_imx241_cpp_video.so \
    vendor/sony/qcom/msm8994/vendor/lib/libchromatix_imx241_default_video.so:system/vendor/lib/libchromatix_imx241_default_video.so \
    vendor/sony/qcom/msm8994/vendor/lib/libchromatix_imx241_liveshot.so:system/vendor/lib/libchromatix_imx241_liveshot.so \
    vendor/sony/qcom/msm8994/vendor/lib/libchromatix_imx241_postproc.so:system/vendor/lib/libchromatix_imx241_postproc.so \
    vendor/sony/qcom/msm8994/vendor/lib/libchromatix_imx241_preview.so:system/vendor/lib/libchromatix_imx241_preview.so \
    vendor/sony/qcom/msm8994/vendor/lib/libchromatix_imx241_snapshot.so:system/vendor/lib/libchromatix_imx241_snapshot.so \
    vendor/sony/qcom/msm8994/vendor/lib/libconfigdb.so:system/vendor/lib/libconfigdb.so \
    vendor/sony/qcom/msm8994/vendor/lib/libdiag.so:system/vendor/lib/libdiag.so \
    vendor/sony/qcom/msm8994/vendor/lib/libdrmfs.so:system/vendor/lib/libdrmfs.so \
    vendor/sony/qcom/msm8994/vendor/lib/libdsi_netctrl.so:system/vendor/lib/libdsi_netctrl.so \
    vendor/sony/qcom/msm8994/vendor/lib/libdsutils.so:system/vendor/lib/libdsutils.so \
    vendor/sony/qcom/msm8994/vendor/lib/libfastcvadsp_stub.so:system/vendor/lib/libfastcvadsp_stub.so \
    vendor/sony/qcom/msm8994/vendor/lib/libfastcvopt.so:system/vendor/lib/libfastcvopt.so \
    vendor/sony/qcom/msm8994/vendor/lib/libflash_pmic.so:system/vendor/lib/libflash_pmic.so \
    vendor/sony/qcom/msm8994/vendor/lib/libidl.so:system/vendor/lib/libidl.so \
    vendor/sony/qcom/msm8994/vendor/lib/libloc_api_v02.so:system/vendor/lib/libloc_api_v02.so \
    vendor/sony/qcom/msm8994/vendor/lib/libloc_ds_api.so:system/vendor/lib/libloc_ds_api.so \
    vendor/sony/qcom/msm8994/vendor/lib/libmdmdetect.so:system/vendor/lib/libmdmdetect.so \
    vendor/sony/qcom/msm8994/vendor/lib/libmiscta.so:system/vendor/lib/libmiscta.so \
    vendor/sony/qcom/msm8994/vendor/lib/libmmcamera2_c2d_module.so:system/vendor/lib/libmmcamera2_c2d_module.so \
    vendor/sony/qcom/msm8994/vendor/lib/libmmcamera2_cpp_module.so:system/vendor/lib/libmmcamera2_cpp_module.so \
    vendor/sony/qcom/msm8994/vendor/lib/libmmcamera2_frame_algorithm.so:system/vendor/lib/libmmcamera2_frame_algorithm.so \
    vendor/sony/qcom/msm8994/vendor/lib/libmmcamera2_iface_modules.so:system/vendor/lib/libmmcamera2_iface_modules.so \
    vendor/sony/qcom/msm8994/vendor/lib/libmmcamera2_imglib_modules.so:system/vendor/lib/libmmcamera2_imglib_modules.so \
    vendor/sony/qcom/msm8994/vendor/lib/libmmcamera2_is.so:system/vendor/lib/libmmcamera2_is.so \
    vendor/sony/qcom/msm8994/vendor/lib/libmmcamera2_isp_modules.so:system/vendor/lib/libmmcamera2_isp_modules.so \
    vendor/sony/qcom/msm8994/vendor/lib/libmmcamera2_pp_buf_mgr.so:system/vendor/lib/libmmcamera2_pp_buf_mgr.so \
    vendor/sony/qcom/msm8994/vendor/lib/libmmcamera2_pproc_modules.so:system/vendor/lib/libmmcamera2_pproc_modules.so \
    vendor/sony/qcom/msm8994/vendor/lib/libmmcamera2_q3a_core.so:system/vendor/lib/libmmcamera2_q3a_core.so \
    vendor/sony/qcom/msm8994/vendor/lib/libmmcamera2_sensor_debug.so:system/vendor/lib/libmmcamera2_sensor_debug.so \
    vendor/sony/qcom/msm8994/vendor/lib/libmmcamera2_sensor_modules.so:system/vendor/lib/libmmcamera2_sensor_modules.so \
    vendor/sony/qcom/msm8994/vendor/lib/libmmcamera2_stats_algorithm.so:system/vendor/lib/libmmcamera2_stats_algorithm.so \
    vendor/sony/qcom/msm8994/vendor/lib/libmmcamera2_stats_modules.so:system/vendor/lib/libmmcamera2_stats_modules.so \
    vendor/sony/qcom/msm8994/vendor/lib/libmmcamera2_vpe_module.so:system/vendor/lib/libmmcamera2_vpe_module.so \
    vendor/sony/qcom/msm8994/vendor/lib/libmmcamera2_wnr_module.so:system/vendor/lib/libmmcamera2_wnr_module.so \
    vendor/sony/qcom/msm8994/vendor/lib/libmmcamera_cac2_lib.so:system/vendor/lib/libmmcamera_cac2_lib.so \
    vendor/sony/qcom/msm8994/vendor/lib/libmmcamera_eeprom_util.so:system/vendor/lib/libmmcamera_eeprom_util.so \
    vendor/sony/qcom/msm8994/vendor/lib/libmmcamera_eztune_module.so:system/vendor/lib/libmmcamera_eztune_module.so \
    vendor/sony/qcom/msm8994/vendor/lib/libmmcamera_faceproc.so:system/vendor/lib/libmmcamera_faceproc.so \
    vendor/sony/qcom/msm8994/vendor/lib/libmmcamera_hdr_gb_lib.so:system/vendor/lib/libmmcamera_hdr_gb_lib.so \
    vendor/sony/qcom/msm8994/vendor/lib/libmmcamera_imglib.so:system/vendor/lib/libmmcamera_imglib.so \
    vendor/sony/qcom/msm8994/vendor/lib/libmmcamera_imx134.so:system/vendor/lib/libmmcamera_imx134.so \
    vendor/sony/qcom/msm8994/vendor/lib/libmmcamera_imx134a.so:system/vendor/lib/libmmcamera_imx134a.so \
    vendor/sony/qcom/msm8994/vendor/lib/libmmcamera_imx200b.so:system/vendor/lib/libmmcamera_imx200b.so \
    vendor/sony/qcom/msm8994/vendor/lib/libmmcamera_imx241.so:system/vendor/lib/libmmcamera_imx241.so \
    vendor/sony/qcom/msm8994/vendor/lib/libmmcamera_isp_abf44.so:system/vendor/lib/libmmcamera_isp_abf44.so \
    vendor/sony/qcom/msm8994/vendor/lib/libmmcamera_isp_bcc44.so:system/vendor/lib/libmmcamera_isp_bcc44.so \
    vendor/sony/qcom/msm8994/vendor/lib/libmmcamera_isp_bf_scale_stats46.so:system/vendor/lib/libmmcamera_isp_bf_scale_stats46.so \
    vendor/sony/qcom/msm8994/vendor/lib/libmmcamera_isp_bf_stats44.so:system/vendor/lib/libmmcamera_isp_bf_stats44.so \
    vendor/sony/qcom/msm8994/vendor/lib/libmmcamera_isp_bg_stats46.so:system/vendor/lib/libmmcamera_isp_bg_stats46.so \
    vendor/sony/qcom/msm8994/vendor/lib/libmmcamera_isp_bhist_stats44.so:system/vendor/lib/libmmcamera_isp_bhist_stats44.so \
    vendor/sony/qcom/msm8994/vendor/lib/libmmcamera_isp_bpc44.so:system/vendor/lib/libmmcamera_isp_bpc44.so \
    vendor/sony/qcom/msm8994/vendor/lib/libmmcamera_isp_chroma_enhan40.so:system/vendor/lib/libmmcamera_isp_chroma_enhan40.so \
    vendor/sony/qcom/msm8994/vendor/lib/libmmcamera_isp_chroma_suppress40.so:system/vendor/lib/libmmcamera_isp_chroma_suppress40.so \
    vendor/sony/qcom/msm8994/vendor/lib/libmmcamera_isp_clamp_encoder40.so:system/vendor/lib/libmmcamera_isp_clamp_encoder40.so \
    vendor/sony/qcom/msm8994/vendor/lib/libmmcamera_isp_clamp_video40.so:system/vendor/lib/libmmcamera_isp_clamp_video40.so \
    vendor/sony/qcom/msm8994/vendor/lib/libmmcamera_isp_clamp_viewfinder40.so:system/vendor/lib/libmmcamera_isp_clamp_viewfinder40.so \
    vendor/sony/qcom/msm8994/vendor/lib/libmmcamera_isp_clf46.so:system/vendor/lib/libmmcamera_isp_clf46.so \
    vendor/sony/qcom/msm8994/vendor/lib/libmmcamera_isp_color_correct46.so:system/vendor/lib/libmmcamera_isp_color_correct46.so \
    vendor/sony/qcom/msm8994/vendor/lib/libmmcamera_isp_color_xform_encoder46.so:system/vendor/lib/libmmcamera_isp_color_xform_encoder46.so \
    vendor/sony/qcom/msm8994/vendor/lib/libmmcamera_isp_color_xform_video46.so:system/vendor/lib/libmmcamera_isp_color_xform_video46.so \
    vendor/sony/qcom/msm8994/vendor/lib/libmmcamera_isp_color_xform_viewfinder46.so:system/vendor/lib/libmmcamera_isp_color_xform_viewfinder46.so \
    vendor/sony/qcom/msm8994/vendor/lib/libmmcamera_isp_cs_stats46.so:system/vendor/lib/libmmcamera_isp_cs_stats46.so \
    vendor/sony/qcom/msm8994/vendor/lib/libmmcamera_isp_demosaic44.so:system/vendor/lib/libmmcamera_isp_demosaic44.so \
    vendor/sony/qcom/msm8994/vendor/lib/libmmcamera_isp_demux40.so:system/vendor/lib/libmmcamera_isp_demux40.so \
    vendor/sony/qcom/msm8994/vendor/lib/libmmcamera_isp_fovcrop_encoder46.so:system/vendor/lib/libmmcamera_isp_fovcrop_encoder46.so \
    vendor/sony/qcom/msm8994/vendor/lib/libmmcamera_isp_fovcrop_video46.so:system/vendor/lib/libmmcamera_isp_fovcrop_video46.so \
    vendor/sony/qcom/msm8994/vendor/lib/libmmcamera_isp_fovcrop_viewfinder46.so:system/vendor/lib/libmmcamera_isp_fovcrop_viewfinder46.so \
    vendor/sony/qcom/msm8994/vendor/lib/libmmcamera_isp_gamma44.so:system/vendor/lib/libmmcamera_isp_gamma44.so \
    vendor/sony/qcom/msm8994/vendor/lib/libmmcamera_isp_gic46.so:system/vendor/lib/libmmcamera_isp_gic46.so \
    vendor/sony/qcom/msm8994/vendor/lib/libmmcamera_isp_gtm46.so:system/vendor/lib/libmmcamera_isp_gtm46.so \
    vendor/sony/qcom/msm8994/vendor/lib/libmmcamera_isp_hdr46.so:system/vendor/lib/libmmcamera_isp_hdr46.so \
    vendor/sony/qcom/msm8994/vendor/lib/libmmcamera_isp_hdr_be_stats46.so:system/vendor/lib/libmmcamera_isp_hdr_be_stats46.so \
    vendor/sony/qcom/msm8994/vendor/lib/libmmcamera_isp_ihist_stats46.so:system/vendor/lib/libmmcamera_isp_ihist_stats46.so \
    vendor/sony/qcom/msm8994/vendor/lib/libmmcamera_isp_linearization40.so:system/vendor/lib/libmmcamera_isp_linearization40.so \
    vendor/sony/qcom/msm8994/vendor/lib/libmmcamera_isp_ltm44.so:system/vendor/lib/libmmcamera_isp_ltm44.so \
    vendor/sony/qcom/msm8994/vendor/lib/libmmcamera_isp_mce40.so:system/vendor/lib/libmmcamera_isp_mce40.so \
    vendor/sony/qcom/msm8994/vendor/lib/libmmcamera_isp_mesh_rolloff44.so:system/vendor/lib/libmmcamera_isp_mesh_rolloff44.so \
    vendor/sony/qcom/msm8994/vendor/lib/libmmcamera_isp_pedestal_correct46.so:system/vendor/lib/libmmcamera_isp_pedestal_correct46.so \
    vendor/sony/qcom/msm8994/vendor/lib/libmmcamera_isp_rs_stats46.so:system/vendor/lib/libmmcamera_isp_rs_stats46.so \
    vendor/sony/qcom/msm8994/vendor/lib/libmmcamera_isp_scaler_encoder46.so:system/vendor/lib/libmmcamera_isp_scaler_encoder46.so \
    vendor/sony/qcom/msm8994/vendor/lib/libmmcamera_isp_scaler_video46.so:system/vendor/lib/libmmcamera_isp_scaler_video46.so \
    vendor/sony/qcom/msm8994/vendor/lib/libmmcamera_isp_scaler_viewfinder46.so:system/vendor/lib/libmmcamera_isp_scaler_viewfinder46.so \
    vendor/sony/qcom/msm8994/vendor/lib/libmmcamera_isp_sce40.so:system/vendor/lib/libmmcamera_isp_sce40.so \
    vendor/sony/qcom/msm8994/vendor/lib/libmmcamera_isp_sub_module.so:system/vendor/lib/libmmcamera_isp_sub_module.so \
    vendor/sony/qcom/msm8994/vendor/lib/libmmcamera_isp_wb46.so:system/vendor/lib/libmmcamera_isp_wb46.so \
    vendor/sony/qcom/msm8994/vendor/lib/libmmcamera_ppbase_module.so:system/vendor/lib/libmmcamera_ppbase_module.so \
    vendor/sony/qcom/msm8994/vendor/lib/libmmcamera_tintless_algo.so:system/vendor/lib/libmmcamera_tintless_algo.so \
    vendor/sony/qcom/msm8994/vendor/lib/libmmcamera_tintless_bg_pca_algo.so:system/vendor/lib/libmmcamera_tintless_bg_pca_algo.so \
    vendor/sony/qcom/msm8994/vendor/lib/libmmcamera_tuning.so:system/vendor/lib/libmmcamera_tuning.so \
    vendor/sony/qcom/msm8994/vendor/lib/libmmcamera_vpu_module.so:system/vendor/lib/libmmcamera_vpu_module.so \
    vendor/sony/qcom/msm8994/vendor/lib/libmmjpeg.so:system/vendor/lib/libmmjpeg.so \
    vendor/sony/qcom/msm8994/vendor/lib/libmmqjpeg_codec.so:system/vendor/lib/libmmqjpeg_codec.so \
    vendor/sony/qcom/msm8994/vendor/lib/libmmqjpegdma.so:system/vendor/lib/libmmqjpegdma.so \
    vendor/sony/qcom/msm8994/vendor/lib/libnetmgr.so:system/vendor/lib/libnetmgr.so \
    vendor/sony/qcom/msm8994/vendor/lib/liboemcamera.so:system/vendor/lib/liboemcamera.so \
    vendor/sony/qcom/msm8994/vendor/lib/libperipheral_client.so:system/vendor/lib/libperipheral_client.so \
    vendor/sony/qcom/msm8994/vendor/lib/libqcci_legacy.so:system/vendor/lib/libqcci_legacy.so \
    vendor/sony/qcom/msm8994/vendor/lib/libqdi.so:system/vendor/lib/libqdi.so \
    vendor/sony/qcom/msm8994/vendor/lib/libqdp.so:system/vendor/lib/libqdp.so \
    vendor/sony/qcom/msm8994/vendor/lib/libqmi.so:system/vendor/lib/libqmi.so \
    vendor/sony/qcom/msm8994/vendor/lib/libqmi_cci.so:system/vendor/lib/libqmi_cci.so \
    vendor/sony/qcom/msm8994/vendor/lib/libqmi_client_helper.so:system/vendor/lib/libqmi_client_helper.so \
    vendor/sony/qcom/msm8994/vendor/lib/libqmi_client_qmux.so:system/vendor/lib/libqmi_client_qmux.so \
    vendor/sony/qcom/msm8994/vendor/lib/libqmi_common_so.so:system/vendor/lib/libqmi_common_so.so \
    vendor/sony/qcom/msm8994/vendor/lib/libqmi_csi.so:system/vendor/lib/libqmi_csi.so \
    vendor/sony/qcom/msm8994/vendor/lib/libqmi_encdec.so:system/vendor/lib/libqmi_encdec.so \
    vendor/sony/qcom/msm8994/vendor/lib/libqmiservices.so:system/vendor/lib/libqmiservices.so \
    vendor/sony/qcom/msm8994/vendor/lib/libqomx_jpegdec.so:system/vendor/lib/libqomx_jpegdec.so \
    vendor/sony/qcom/msm8994/vendor/lib/libqomx_jpegenc.so:system/vendor/lib/libqomx_jpegenc.so \
    vendor/sony/qcom/msm8994/vendor/lib/libqomx_jpegenc_pipe.so:system/vendor/lib/libqomx_jpegenc_pipe.so \
    vendor/sony/qcom/msm8994/vendor/lib/libril-qc-qmi-1.so:system/vendor/lib/libril-qc-qmi-1.so \
    vendor/sony/qcom/msm8994/vendor/lib/libril-qc-qmi-2.so:system/vendor/lib/libril-qc-qmi-2.so \
    vendor/sony/qcom/msm8994/vendor/lib/libril-qcril-hook-oem.so:system/vendor/lib/libril-qcril-hook-oem.so \
    vendor/sony/qcom/msm8994/vendor/lib/librpmb.so:system/vendor/lib/librpmb.so \
    vendor/sony/qcom/msm8994/vendor/lib/libsensor1.so:system/vendor/lib/libsensor1.so \
    vendor/sony/qcom/msm8994/vendor/lib/libsensor_reg.so:system/vendor/lib/libsensor_reg.so \
    vendor/sony/qcom/msm8994/vendor/lib/libsmemlog.so:system/vendor/lib/libsmemlog.so \
    vendor/sony/qcom/msm8994/vendor/lib/libssd.so:system/vendor/lib/libssd.so \
    vendor/sony/qcom/msm8994/vendor/lib/libsystem_health_mon.so:system/vendor/lib/libsystem_health_mon.so \
    vendor/sony/qcom/msm8994/vendor/lib/libta.so:system/vendor/lib/libta.so \
    vendor/sony/qcom/msm8994/vendor/lib/libtime_genoff.so:system/vendor/lib/libtime_genoff.so \
    vendor/sony/qcom/msm8994/vendor/lib/libxml.so:system/vendor/lib/libxml.so \
    vendor/sony/qcom/msm8994/vendor/lib64/hw/sensors.msm8994.so:system/vendor/lib64/hw/sensors.msm8994.so \
    vendor/sony/qcom/msm8994/vendor/lib64/libQSEEComAPI.so:system/vendor/lib64/libQSEEComAPI.so \
    vendor/sony/qcom/msm8994/vendor/lib64/libadsprpc.so:system/vendor/lib64/libadsprpc.so \
    vendor/sony/qcom/msm8994/vendor/lib64/libconfigdb.so:system/vendor/lib64/libconfigdb.so \
    vendor/sony/qcom/msm8994/vendor/lib64/libdiag.so:system/vendor/lib64/libdiag.so \
    vendor/sony/qcom/msm8994/vendor/lib64/libdrmfs.so:system/vendor/lib64/libdrmfs.so \
    vendor/sony/qcom/msm8994/vendor/lib64/libdsi_netctrl.so:system/vendor/lib64/libdsi_netctrl.so \
    vendor/sony/qcom/msm8994/vendor/lib64/libdsutils.so:system/vendor/lib64/libdsutils.so \
    vendor/sony/qcom/msm8994/vendor/lib64/libidl.so:system/vendor/lib64/libidl.so \
    vendor/sony/qcom/msm8994/vendor/lib64/libloc_api_v02.so:system/vendor/lib64/libloc_api_v02.so \
    vendor/sony/qcom/msm8994/vendor/lib64/libloc_ds_api.so:system/vendor/lib64/libloc_ds_api.so \
    vendor/sony/qcom/msm8994/vendor/lib64/libmdmdetect.so:system/vendor/lib64/libmdmdetect.so \
    vendor/sony/qcom/msm8994/vendor/lib64/libmiscta.so:system/vendor/lib64/libmiscta.so \
    vendor/sony/qcom/msm8994/vendor/lib64/libmmcamera2_sensor_debug.so:system/vendor/lib64/libmmcamera2_sensor_debug.so \
    vendor/sony/qcom/msm8994/vendor/lib64/libnetmgr.so:system/vendor/lib64/libnetmgr.so \
    vendor/sony/qcom/msm8994/vendor/lib64/libperipheral_client.so:system/vendor/lib64/libperipheral_client.so \
    vendor/sony/qcom/msm8994/vendor/lib64/libqcci_legacy.so:system/vendor/lib64/libqcci_legacy.so \
    vendor/sony/qcom/msm8994/vendor/lib64/libqdi.so:system/vendor/lib64/libqdi.so \
    vendor/sony/qcom/msm8994/vendor/lib64/libqdp.so:system/vendor/lib64/libqdp.so \
    vendor/sony/qcom/msm8994/vendor/lib64/libqmi.so:system/vendor/lib64/libqmi.so \
    vendor/sony/qcom/msm8994/vendor/lib64/libqmi_cci.so:system/vendor/lib64/libqmi_cci.so \
    vendor/sony/qcom/msm8994/vendor/lib64/libqmi_client_helper.so:system/vendor/lib64/libqmi_client_helper.so \
    vendor/sony/qcom/msm8994/vendor/lib64/libqmi_client_qmux.so:system/vendor/lib64/libqmi_client_qmux.so \
    vendor/sony/qcom/msm8994/vendor/lib64/libqmi_common_so.so:system/vendor/lib64/libqmi_common_so.so \
    vendor/sony/qcom/msm8994/vendor/lib64/libqmi_csi.so:system/vendor/lib64/libqmi_csi.so \
    vendor/sony/qcom/msm8994/vendor/lib64/libqmi_encdec.so:system/vendor/lib64/libqmi_encdec.so \
    vendor/sony/qcom/msm8994/vendor/lib64/libqmiservices.so:system/vendor/lib64/libqmiservices.so \
    vendor/sony/qcom/msm8994/vendor/lib64/libril-qc-qmi-1.so:system/vendor/lib64/libril-qc-qmi-1.so \
    vendor/sony/qcom/msm8994/vendor/lib64/libril-qc-qmi-2.so:system/vendor/lib64/libril-qc-qmi-2.so \
    vendor/sony/qcom/msm8994/vendor/lib64/libril-qcril-hook-oem.so:system/vendor/lib64/libril-qcril-hook-oem.so \
    vendor/sony/qcom/msm8994/vendor/lib64/librpmb.so:system/vendor/lib64/librpmb.so \
    vendor/sony/qcom/msm8994/vendor/lib64/libsensor1.so:system/vendor/lib64/libsensor1.so \
    vendor/sony/qcom/msm8994/vendor/lib64/libsensor_reg.so:system/vendor/lib64/libsensor_reg.so \
    vendor/sony/qcom/msm8994/vendor/lib64/libsmemlog.so:system/vendor/lib64/libsmemlog.so \
    vendor/sony/qcom/msm8994/vendor/lib64/libssd.so:system/vendor/lib64/libssd.so \
    vendor/sony/qcom/msm8994/vendor/lib64/libsystem_health_mon.so:system/vendor/lib64/libsystem_health_mon.so \
    vendor/sony/qcom/msm8994/vendor/lib64/libta.so:system/vendor/lib64/libta.so \
    vendor/sony/qcom/msm8994/vendor/lib64/libtime_genoff.so:system/vendor/lib64/libtime_genoff.so \
    vendor/sony/qcom/msm8994/vendor/lib64/libxml.so:system/vendor/lib64/libxml.so
